name: Deploy to Docker Hub

on:
  push:
    branches:
      - deploy-mac

jobs:
  send-notification-started:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *ğŸš€ Database Change Bot* ğŸƒâ€â™‚ï¸${{ github.run_number }}

            *ğŸ‘¤ Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *ğŸ“ Commit message:* ${{ github.event.commits[0].message }}
            *ğŸ“¦ Repository:* ${{ github.repository }}
            *ğŸ” See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            Started ğŸšï¸ï¸ï¸ï¸ï¸ï¸ğŸšï¸ï¸ï¸ï¸ï¸ï¸ğŸšï¸ï¸ï¸ï¸ï¸ï¸ğŸšï¸ï¸ï¸ï¸ï¸ï¸

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker buildx create --name builder --use
          docker buildx inspect builder --bootstrap
          docker buildx build -t ideavn/db-change-bot:latest --push .
      
      - name: Remote ssh to pull and run docker
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
          CONFIG_FILE_CONTENT: ${{ secrets.CONFIG_FILE_CONTENT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MAC }}
          username: ${{ secrets.SSH_USER_NAME_MAC }}
          password: ${{ secrets.SSH_PASSWORD_MAC }}
          port: ${{ secrets.SSH_PORT }}
          envs: ENV_FILE_CONTENT, CONFIG_FILE_CONTENT
          script: |
            echo "$ENV_FILE_CONTENT" > /tmp/.env
            echo "$CONFIG_FILE_CONTENT" > /tmp/config.json
            /usr/local/bin/docker stop db-change-bot
            /usr/local/bin/docker rm db-change-bot
            /usr/local/bin/docker pull ideavn/db-change-bot
            /usr/local/bin/docker run -d --name db-change-bot --env-file /tmp/.env --restart always ideavn/db-change-bot
            /usr/local/bin/docker cp /tmp/config.json db-change-bot:/usr/src/app/dist/config.json
            rm -rf /tmp/.env
            rm -rf /tmp/config.json
            /usr/local/bin/docker image prune -a -f

  send-notification-successful:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() && needs.build.result == 'success' }}
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *ğŸ‰ Database Change Bot Deployment Successful*  
            
            *ğŸ‘¤ Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *ğŸ“ Commit message:* ${{ github.event.commits[0].message }}
            *ğŸ“¦ Repository:* ${{ github.repository }}
            *ğŸ” See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})
            ğŸš€ï¸ï¸ï¸ï¸ï¸ï¸ğŸš€ï¸ï¸ï¸ï¸ï¸ï¸ğŸš€ï¸ï¸ï¸ï¸ï¸ï¸ğŸš€ï¸ï¸ï¸ï¸ï¸ï¸ğŸš€ï¸ï¸ï¸ï¸ï¸ï¸ğŸš€ï¸ï¸ï¸ï¸ï¸ï¸

  send-notification-deploy-failed:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ failure() && needs.build.result == 'failure' }}
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *âŒ Database Change Bot Deployment Failed*  
            
            *ğŸ‘¤ Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *ğŸ“ Commit message:* ${{ github.event.commits[0].message }}
            *ğŸ“¦ Repository:* ${{ github.repository }}
            *ğŸ” See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})
            ğŸ˜ï¸ï¸ï¸ï¸ï¸ï¸ğŸ˜ï¸ï¸ï¸ï¸ï¸ï¸ğŸ˜ï¸ï¸ï¸ï¸ï¸ï¸ğŸ˜ï¸ï¸ï¸ï¸ï¸ï¸ğŸ˜ï¸ï¸ï¸ï¸ï¸ï¸ğŸ˜ï¸ï¸ï¸ï¸ï¸ï¸
